os:
  - osx
language: swift
sudo: required
osx_image: xcode11.5
script:
  - set -o pipefail
  - xcodebuild -project MarvelHeroes.xcodeproj -scheme "MarvelHeroes"  -sdk iphonesimulator  -destination 'platform=iOS Simulator,name=iPhone 11,OS=13.5' test
notifications:
  email:
    on_success: never
    on_failure: change
